### ISSUE TITLE
crashing Godot 3.1 stable on Windows

### ISSUE THREAD

**Issue by j2l** [SimonSikstrom/godot-midi-in-module#2]
I can't open the example project on Windows 10Pro and can't see the console window before it crashes and self quit.

**Comment by SimonSikstrom** [comment]
What do the crash log say?

**Comment by j2l** [comment]
No crash log written AFAIK. Do you know the windows file path for this kind of "crashing while opening" event?

**Comment by SimonSikstrom** [comment]
I haven't tried to compile Godot on Windows myself so I can't really say. On second thought I don't think the example can work on win10 anyway since the module is not targeted to build on windows. 

```
From midiIn/config.py:

def can_build(env, plat):
	return plat == "android" or plat == "iphone" or plat == "osx"
```

If you want, you could try to ```return true``` in the ```can_build``` method, recompile, and see if it works.

**Comment by j2l** [comment]
Too bad. I guess I'll wait for another midi project I think
