### ISSUE TITLE
MIDI file -> Godot?

### ISSUE THREAD

**Issue by xicus** [SimonSikstrom/godot-midi-in-module#3]
Hi! Sorry to reach out this way, but you're the first person I've found working with MIDI in Godot. I'm probably an intermediate scripter, but looking for a way to ingest MIDI files for use in rhythm game mechanics. If you could point me in the right direction or offer advice, I'd appreciate it 😊 I'm hoping to synch MIDI note tracks with an audio file. --davidicus, macrocephalia@gmail.com

**Comment by SimonSikstrom** [comment]
Hey, you're probably looking for midi playback. This is only for capturing midi signals from midi devices on Android/iOS.
Try searching for something like:
https://www.google.com/search?q=midi+playback+godot&oq=midi+playback+godot&aqs=chrome..69i57j69i60.5151j0j7&sourceid=chrome&ie=UTF-8
